package com.funjson.metaagent.intent.domain;

import java.util.List;
import java.util.Locale;

/**
 * Stable task categories recognized at turn-orchestration time.
 *
 * <p>Labels remain useful as extensible metadata, but high-level routing must
 * not depend only on free-form labels. This enum provides a durable vocabulary
 * for mixed-intent splitting, dependency reasoning and later Job creation.</p>
 */
public enum TurnTaskType {
    /** Ordinary conversation or small talk. */
    GENERAL_CHAT,
    /** Text generation that does not require external fresh data. */
    TEXT_GENERATION,
    /** Resume, self-introduction or personal profile generation. */
    RESUME_OR_PROFILE_GENERATION,
    /** Weather query that should normally use the weather tool. */
    WEATHER_QUERY,
    /** Quick web search or search-backed question answering. */
    WEB_SEARCH,
    /** Multi-source research or deep-research work. */
    DEEP_RESEARCH,
    /** Question answering over uploaded or local files. */
    FILE_QA,
    /** File read/write or transformation work. */
    FILE_OPERATION,
    /** Explicit tool-backed operation that does not fit a narrower type. */
    TOOL_ACTION,
    /** A structured answer to an open pending interaction. */
    CLARIFICATION_ANSWER,
    /** Control command such as pause, cancel, resume or status. */
    CONTROL_COMMAND,
    /** Fallback for valid but not yet classified tasks. */
    UNKNOWN;

    /**
     * Infers a stable task type from the existing action metadata.
     *
     * @param action action generated by the understanding pipeline
     * @return inferred task type
     */
    public static TurnTaskType infer(TurnAction action) {
        if (action == null) {
            return UNKNOWN;
        }
        if (action.actionType() == TurnActionType.ANSWER_PENDING) {
            return CLARIFICATION_ANSWER;
        }
        if (action.actionType() == TurnActionType.CONTROL_MESSAGE) {
            return CONTROL_COMMAND;
        }
        String text = normalizedText(action);
        List<String> labels = action.recognition() == null
                ? List.of()
                : action.recognition().labels();
        if (containsAny(labels, "weather")
                || text.contains("天气")
                || text.contains("weather")) {
            return WEATHER_QUERY;
        }
        if (containsAny(labels, "research-depth:deep-research")
                || text.contains("deepresearch")
                || text.contains("深度调研")
                || text.contains("深度研究")) {
            return DEEP_RESEARCH;
        }
        if (containsAny(labels, "needs-web", "needs-fresh-info")) {
            return WEB_SEARCH;
        }
        if (containsAny(labels, "needs-file-context", "file")
                || text.contains("文件")
                || text.contains("上传")) {
            return FILE_QA;
        }
        if (text.contains("简历")
                || text.contains("个人介绍")
                || text.contains("自我介绍")
                || text.contains("resume")
                || text.contains("profile")) {
            return RESUME_OR_PROFILE_GENERATION;
        }
        if (action.actionType() == TurnActionType.CREATE_JOB) {
            return TEXT_GENERATION;
        }
        return UNKNOWN;
    }

    /**
     * Builds normalized searchable text for inference.
     */
    private static String normalizedText(TurnAction action) {
        String recognitionText = action.recognition() == null
                ? ""
                : "%s %s %s".formatted(
                        action.recognition().goalSummary(),
                        action.recognition().decisionSummary(),
                        String.join(" ", action.recognition().labels()));
        return "%s %s %s %s".formatted(
                        action.sourceSpan(),
                        action.originalText(),
                        action.canonicalGoal(),
                        recognitionText)
                .replaceAll("\\s+", "")
                .toLowerCase(Locale.ROOT);
    }

    /**
     * Checks whether labels contain any expected label.
     */
    private static boolean containsAny(List<String> labels, String... expected) {
        List<String> normalized = labels.stream()
                .map(label -> label.toLowerCase(Locale.ROOT))
                .toList();
        for (String candidate : expected) {
            if (normalized.contains(candidate.toLowerCase(Locale.ROOT))) {
                return true;
            }
        }
        return false;
    }
}
